"""add_outbox_status_indexing

Revision ID: 6c76bdc0fb5a
Revises: b3a202fdebdb
Create Date: 2026-05-04 13:53:25.599949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c76bdc0fb5a'
down_revision: Union[str, Sequence[str], None] = 'b3a202fdebdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_outboxs_status'), 'outboxs', ['status'], unique=False)
    op.create_unique_constraint(None, 'outboxs', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'outboxs', type_='unique')
    op.drop_index(op.f('ix_outboxs_status'), table_name='outboxs')
    # ### end Alembic commands ###
